### ISSUE TITLE
not working on yosemite for me

### ISSUE THREAD

**Issue by Ahti** [amyworrall/QuickRadar#61]
I'm trying to use QuickRadar on Yosemite (DP 3), But can't get it to work.

I tried the latest build from the development branch. The status item works. When I click "preferences" in the menu, the frontmost window looses focus, but no settings window appears. When I click "new radar", the window for creating a new radar briefly shows, then disappears again.

**Comment by Keithbsmiley** [comment]
Seems to be working fine for me on the release builds. @Ahti is this still an issue?

**Comment by Ahti** [comment]
I didn't try submitting anything, but the windows open as expectefd :+1:

(Sorry for taking so long to respond :sweat_smile:)
