### ISSUE TITLE
Support for two-step authentication?

### ISSUE THREAD

**Issue by DeepFriedPotato** [amyworrall/QuickRadar#86]
Seems like QuickRadar does not support two-step authentication? Or is something wrong with my setup? I'm getting Authentication Error.

**Comment by rnapier** [comment]
Apple indicates that you can [use app-specific passwords](https://support.apple.com/en-us/HT204397) for this case. However, I haven't been able to get this to work so far (for anything, not just QR).

**Comment by dlo** [comment]
Ditto. Created an app-specific password and getting an authentication failed dialog.

**Comment by fjcaetano** [comment]
Same here. Also, I'm not being able to log into Apple's Bug Report with the generated password. I believe the issue may be in the bug report tool itself.

**Comment by an0** [comment]
I believe you are talking about two-factor authentication instead of two-step authentication. I just switch from two-step authentication to two-factor authentication for my account and suddenly QuickRadar stops working.

**Comment by hariseldon78** [comment]
same problem for me; i get the authorization popup on mac, the same popup on iphone(wtf?) both devices give me the code, none gives me the textfield; i don't know where i'm supposed to enter that code... and in the mean time quick radar times out.

**Comment by dlo** [comment]
@hariseldon78 Just type the OTP code after your password. I believe that should let you log in.

**Comment by philosopherdog** [comment]
Having the same issues as @hariseldon78 .
