### ISSUE TITLE
Unable to post: too many HTTP redirects

### ISSUE THREAD

**Issue by phatblat** [amyworrall/QuickRadar#91]
Attempting to post a new radar gives the following error message:

![screen shot 2016-06-23 at 10 38 06 am](https://cloud.githubusercontent.com/assets/28851/16311648/a0586480-392e-11e6-9cd4-a30cb19e0a89.png)

This happens even when none of the cross-posting options actions (copy to clipboard, send to open radar, post to twitter) are selected.

Error occurs on 3 different Mac using both

- OS X 10.11.5
- macOS 10.12 beta 1

**Comment by guillaume-algis** [comment]
See https://github.com/amyworrall/QuickRadar/issues/89, which was fixed by https://github.com/amyworrall/QuickRadar/pull/90 a few hours ago.

**Comment by chockenberry** [comment]
It looks like this problem was *not* fixed by #90. See comments at the end of #89.
