### ISSUE TITLE
add version release notes to Sparkle feed

### ISSUE THREAD

**Issue by workflowsguy** [amyworrall/QuickRadar#93]
It would be great if the Sparkle feed could be augmented by a description for each new release.

Thanks for creating QuickRadar!

**Comment by amyworrall** [comment]
Hi @workflowsguy,

I do provide release notes on the Sparkle feed. For instance, the notes for 1.0b3 say "Fixes from Matej Bukovinski to accommodate changes to Apple's bug reporter website." 

In the appcast feed, they're tagged as `<sparkle:releaseNotesLink>`.

Are they not showing up for you?

Amy

**Comment by workflowsguy** [comment]
Apologies for raising a false alarm. 

When opening the Sparkle feed in the Browser, only the contents of `description` tags are displayed; I forgot to look at the source to see that you use separate description pages with`releaseNotesLink`for documentation.

Thanks!
